spring:
  application:
    name: becareful-server
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT:3306}/${DATABASE_NAME}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    include:
      - oauth2
      - sms
      - redis
      - s3
    active: local

jwt:
  secret: "${JWT_SECRET_KEY}"
  expiration_time:
    access_token: 86400
    refresh_token: 604800

server:
  tomcat:
    uri-encoding: UTF-8

login:
  redirect_url:
    guest: "${LOGIN_REDIRECT_URL_GUEST}"
    user: "${LOGIN_REDIRECT_URL_USER}"



cookie:
  secure: "${COOKIE_SECURE}"
  samesite: "${COOKIE_SAMESITE}"
